### ISSUE TITLE
Missing Windows Dependency in Building MD doc

### ISSUE THREAD

**Issue by Therzok** [mono/md-website#1]
[This](https://github.com/mono/md-website/blob/gh-pages/developers/building-monodevelop.md#prerequisites-and-source) lacks the link to [MonoLibraries](http://monodevelop.com/files/Windows/MonoLibraries.msi). Tracking it down here.

**Comment by Therzok** [comment]
The file is gone from the old url.

Here is the new one.
https://web.archive.org/web/20140101080121/http://monodevelop.com/files/Windows/MonoLibraries.msi

**Comment by akoeplinger** [comment]
What is the MonoLibraries package doing?

**Comment by Therzok** [comment]
From what I observed, it adds build dependencies required by MonoDevelop to the GAC. I'm considering some other method of getting those up, but for now, we should have that msi.

**Comment by akoeplinger** [comment]
Ah, ok. I had a quick look at the msi and it seems to mostly contain Mono.Addins. I think we could get that e.g. from [NuGet](https://nuget.org/packages/Mono.Addins) in the future?

**Comment by Therzok** [comment]
I think the reason Mono.Addins was in there was because there had to be a way to create mono addins without having to locally copy the assembly to every project. But I think NuGet is the way to go now. Regardless, until a resolution is found, that msi should still exist.

**Comment by garuma** [comment]
Can we fix this problem please? Currently there is no way for a newcomer to setup a Windows environment because of this.

@akoeplinger ?

**Comment by akoeplinger** [comment]
@garuma Can we host the MSI on a Xamarin server somewhere so we don't need to get it from archive.org?

**Comment by garuma** [comment]
Yep, I'm doing that now, will give you the link in a sec

**Comment by garuma** [comment]
You can use https://files.xamarin.com/~jeremie/MonoLibraries.msi for now.

I took the source from the archive.org link

**Comment by akoeplinger** [comment]
I added the link, but I think the correct fix long-term is to move those dependencies to NuGet, so I'm inclined to leave this issue open for now to track it.

**Comment by garuma** [comment]
Fair enough.

My intention was to de-block the situation but it's definitely not a long-term fix.

**Comment by garuma** [comment]
Thanks for the quick change btw, much appreciated.

**Comment by directhex** [comment]
I'm closing this - turns out MonoLibraries.msi isn't actually needed these days (it mostly contained Mono.Addins, which is now a submodule). Other libs in MonoLibraries responsible for optional extensions should be fixed to no longer require _bundled libraries from Mono 2.6_

**Comment by Therzok** [comment]
@directhex I'm currently taking a look at removing those dependencies.
