### ISSUE TITLE
Windows section outdated

### ISSUE THREAD

**Issue by yihuajack** [mono/md-website#118]
1. The link in the bullet "Install the Mono libraries package (installer)" "https://files.xamarin.com/~jeremie/MonoLibraries.msi" is no longer accessible;
2. The link in the bullet "Install GNU Gettext tools (from here)" "http://gnuwin32.sourceforge.net/packages/gettext.htm" seems too old (last changed 6 May 2005). A newer version published on 2020-08-12 https://mlocati.github.io/articles/gettext-iconv-windows.html is available.

**Comment by lextm** [comment]
https://blog.lextudio.com/the-end-of-monodevelop-80b383dab34b If you don't know yet.

**Comment by yihuajack** [comment]
Thanks for your information.
