### ISSUE TITLE
Tarballs do not get updated

### ISSUE THREAD

**Issue by Mailaender** [mono/md-website#12]
Tarballs from http://download.mono-project.com/sources/monodevelop/ are either broken or do not get updated at all. This is a problem for Linux package maintainers.

**Comment by akoeplinger** [comment]
Does this apply to the latest one (5.5.0.227) as well or just the older ones?

/cc @directhex

**Comment by Mailaender** [comment]
It says

> The latest stable release is **5.5.4**.

but the latest tarball is 5.5.0.227 from 2 months ago and does not compile. https://bugzilla.xamarin.com/show_bug.cgi?id=23696

**Comment by akoeplinger** [comment]
AFAIK, the 5.5.0->5.5.4 release only contained Mac changes, that's why no tarball was released. But 5.5.0.227 should of course compile, let's see what @directhex says about this.

**Comment by Mailaender** [comment]
Maybe the homepage could indicate that. "The latest Linux release is 5.5.0" or something.

**Comment by Mailaender** [comment]
He helped me resolve https://bugzilla.xamarin.com/show_bug.cgi?id=23696. Documentation about what is the latest version for which operating system and a changelog especially in regards of dependencies is still missing though.
