### ISSUE TITLE
Markdown tables are not rendering

### ISSUE THREAD

**Issue by Therzok** [mono/md-website#2]
Probably the format for tables in MD requires column descriptions. Tables used in [API Overview](https://github.com/mono/md-website/blob/gh-pages/developers/articles/api-overview.md) don't have such data and they won't render.

Also, the html formatting is rendered as plain text if you make it work as a table.

**Comment by thiagojedi** [comment]
The Github preview doesn't render tables.

But when you go to the [compiled page](http://mono.github.io/md-website/developers/articles/api-overview/) you'll see it is ok.

**Comment by Therzok** [comment]
Oh. I didn't check that. Guess it's time to contact GH support.

Thanks.
