### ISSUE TITLE
Xamarin Studio. Cound not launch web server.

### ISSUE THREAD

**Issue by edsokolova** [mono/md-website#50]
I'm trying to remote debugging. But I can't...

Steps (using Windows):
1. I set an environment variable named MONODEVELOP_SDB_TEST to 1.
2. Open project.
3. Run -> Run With -> Custom Command Mono Soft Debugger.
4. Write IP, Port. 
5. Click 'Listen' (or 'Connect', have the same problem).

After that I have a message:
"Could not launch web server. Unable to cast object of type 'MonoDevelop.AspNet.Execution.AspNetExecutionCommand' to type  'MonoDevelop.Core.Execution.DotNetExecutionCommand' ".

**Comment by nikhil850144** [comment]
i experience same issue with mono develop 5.10.0 on Linux any update on this issue ?

**Comment by akoeplinger** [comment]
This issue was moved to mono/monodevelop#4097
