### ISSUE TITLE
The C++ binding article should be brought offline

### ISSUE THREAD

**Issue by lextm** [mono/md-website#56]
https://github.com/mono/md-website/blob/gh-pages/documentation/creating-c-and-cpp-projects.md

As [C++ binding has been removed](https://github.com/mono/monodevelop/commit/792f48882e650ac76cde4107211e644845895d6a) and [the separate repo is idle](https://github.com/mhutch/cbinding), I think the above article should be brought offline to avoid confusion.

**Comment by DayBr3ak** [comment]
I second this, just downloaded monodevelop for cpp and it's just not in the ide anymore.
