### ISSUE TITLE
Current state of UI support

### ISSUE THREAD

**Issue by ShalokShalom** [mono/md-website#69]
https://github.com/ddobrev/QtSharp/issues/67

**Comment by akoeplinger** [comment]
It looks like you got an answer on that QtSharp thread, closing this one :)

**Comment by ShalokShalom** [comment]
Its about updating the website?

**Comment by akoeplinger** [comment]
Sorry, that wasn't clear from the description. I guess you'll get a better answer about adding QtSharp to the IDE by filing an issue in the main MonoDevelop repo instead of on the website: https://github.com/mono/monodevelop.

**Comment by ShalokShalom** [comment]
Its not about adding it to the IDE.
Its about adding it to the website.
Since the website hosts a list of all supported UI toolkits. There is no reason to technically integrate it, at least from my view?

**Comment by akoeplinger** [comment]
which page did you have in mind? feel free to send a pull request with the proposed changes and we can discuss there
