### ISSUE TITLE
404 on pages

### ISSUE THREAD

**Issue by Xoristzatziki** [mono/md-website#95]
Some links on pages for documentation are directing to "404 Not Found".
Most of them are directing to http://www.go-mono.com/md/screencasts (like the Packaging.ogg found in https://github.com/mono/md-website/blob/gh-pages/documentation/building-packages-with-monodevelop.md )

If these files are no longer available please remove them. Or point here where these files are in order to be changed by any volunteer.

**Comment by akoeplinger** [comment]
I fixed the Packaging.ogg link, please let me know if you see more 404s.
